---
title: "PEtests"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sdt <- data.frame(time = rep(1:10, 3), id = c(rep(1, 10), rep(2, 10), rep(3, 10)) , treatment = 0, outcome = runif(30))
sdt$treatment[5] <- 1
treateds <- findAllTreated(sdt, unit.var = 'id', treatedvar = "treatment", time.var = "time")
sample_sets <- get.matchedsets(t = treateds$time, id = treateds$id, data = sdt, t.column = "time", id.column = "id", treatedvar = "treatment", L = 4)
attr(sample_sets[[1]], "weights") <- rep(1/2, 2) #simple equal weight scheme

debug(PanelEstimate2)
testpe <- PanelEstimate2(0:4, "bootstrap", sets = sample_sets, qoi = "att", data = sdt, outcome.variable = "outcome") #does data need to be sorted? 
##nothing should change after prep_for_leads
```

larger data set to better test dropping, keeping of variables
```{r}
sdt <- data.frame(time = rep(1:10, 6), id = c(rep(1, 10), rep(2, 10), rep(3, 10), rep(4, 10), rep(5, 10), rep(6, 10)) , treatment = 0, outcome = runif(60))
sdt$treatment[c(5, 15, 45)] <- 1
treateds <- findAllTreated(sdt, unit.var = 'id', treatedvar = "treatment", time.var = "time")
sample_sets <- get.matchedsets(t = treateds$time, id = treateds$id, data = sdt, t.column = "time", id.column = "id", treatedvar = "treatment", L = 4)
s<- lapply(sample_sets, FUN = function(x) { attr(x, "weights") <-rep(1/3, 3); return(x); })
attributes(s) <- attributes(sample_sets) #fill in rest of attributes
testpe <- PanelEstimate2(0:4, "bootstrap", sets = s, qoi = "att", data = sdt, outcome.variable = "outcome") #does data need to be sorted? 
```

```{r}
sdt <- data.frame(time = rep(1:10, 6), id = c(rep(1, 10), rep(2, 10), rep(3, 10), rep(4, 10), rep(5, 10), rep(6, 10)) , treatment = 0, outcome = runif(60))
sdt$treatment[c(5, 15, 45)] <- 1
sdt <- sdt[-6, ] # treatment unit missing info at t + 1
treateds <- findAllTreated(sdt, unit.var = 'id', treatedvar = "treatment", time.var = "time")
sample_sets <- get.matchedsets(t = treateds$time, id = treateds$id, data = sdt, t.column = "time", id.column = "id", treatedvar = "treatment", L = 4)
s<- lapply(sample_sets, FUN = function(x) { attr(x, "weights") <-rep(1/3, 3); return(x); })
attributes(s) <- attributes(sample_sets) #fill in rest of attributes
testpe <- PanelEstimate2(0:4, "bootstrap", sets = s, qoi = "att", data = sdt, outcome.variable = "outcome")
```
```{r}
sdt <- data.frame(time = rep(1:10, 6), id = c(rep(1, 10), rep(2, 10), rep(3, 10), rep(4, 10), rep(5, 10), rep(6, 10)) , treatment = 0, outcome = runif(60))
sdt$treatment[c(5, 15, 45)] <- 1
sdt$outcome[36] <- NA
treateds <- findAllTreated(sdt, unit.var = 'id', treatedvar = "treatment", time.var = "time")
sample_sets <- get.matchedsets(t = treateds$time, id = treateds$id, data = sdt, t.column = "time", id.column = "id", treatedvar = "treatment", L = 4)
s<- lapply(sample_sets, FUN = function(x) { attr(x, "weights") <-rep(1/3, 3); return(x); })
attributes(s) <- attributes(sample_sets) #fill in rest of attributes
testpe <- PanelEstimate2(0:4, "bootstrap", sets = s, qoi = "att", data = sdt, outcome.variable = "outcome")
```

```{r}
sdt <- data.frame(time = rep(1:10, 6), id = c(rep(1, 10), rep(2, 10), rep(3, 10), rep(4, 10), rep(5, 10), rep(6, 10)) , treatment = 0, outcome = runif(60))
sdt$treatment[c(5, 13, 15)] <- 1
sdt$treatment[c(23, 33)] <- 1
sdt$outcome[56] <- NA
treateds <- findAllTreated(sdt, unit.var = 'id', treatedvar = "treatment", time.var = "time")
sample_sets <- get.matchedsets(t = treateds$time, id = treateds$id, data = sdt, t.column = "time", id.column = "id", treatedvar = "treatment", L = 2)
s<- lapply(sample_sets, FUN = function(x) { attr(x, "weights") <-rep(1 / length(x), length(x)); return(x); })
attributes(s) <- attributes(sample_sets) #fill in rest of attributes
testpe <- PanelEstimate2(0:4, "bootstrap", sets = s, qoi = "att", data = sdt, outcome.variable = "outcome")
```


```{r}
sdt <- data.frame(time = rep(1:10, 6), id = c(rep(1, 10), rep(2, 10), rep(3, 10), rep(4, 10), rep(5, 10), rep(6, 10)) , treatment = 0, outcome = runif(60))
sdt$treatment[c(5, 13, 15)] <- 1
sdt$treatment[c(23, 33)] <- 1
sdt$outcome[56] <- NA
sdt$outcome[26] <- NA
treateds <- findAllTreated(sdt, unit.var = 'id', treatedvar = "treatment", time.var = "time")
sample_sets <- get.matchedsets(t = treateds$time, id = treateds$id, data = sdt, t.column = "time", id.column = "id", treatedvar = "treatment", L = 2)
s<- lapply(sample_sets, FUN = function(x) { attr(x, "weights") <-rep(1 / length(x), length(x)); return(x); })
attributes(s) <- attributes(sample_sets) #fill in rest of attributes
testpe <- PanelEstimate2(0:4, "bootstrap", sets = s, qoi = "att", data = sdt, outcome.variable = "outcome")
```

